# -*- coding: utf-8 -*-
"""OOP Class-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139JoKmowCFhXAQeSEUyaVXejrrNYk2GX
"""

## Robot 1
def movement_1():
  print("its Robot 1")

def fire_detect1():
  print("its Robot 1")

def wheel_control_1():
  print("its Robot 1")


## Robot 2

def movement_2():
  print("its Robot 2")

def fire_detect_2():
  print("its Robot 2")

def wheel_control_2():
  print("its Robot 2")

movement_1()

movement_2()

# using OOP
class Robot:
    def __init__(self, robot_number):
        self.robot_number = robot_number

    def movement(self):
        print(f"Its robot {self.robot_number}")

    def fire_detect(self):
        print(f"Its robot {self.robot_number}")

    def wheel_control(self):
        print(f"Its robot {self.robot_number}")

robot1 = Robot(robot_number=1)

robot1.movement()

robot1.fire_detect()

robot1.wheel_control()

l = [1,2,3,4]
l.upper()

s = "Rakib"
s.append("F")



l = [1,2,3,4]
print(type(l))



s = "Inception bd"
print(type(s))



a = 66
print(type(a))

l = list()
s = str()

print(type(s))

print(type(l))

samsung = mobile()
iphone = mobile()
vivo = mobile()

bmw = car()
audi = car()

